version: '3.3'
services:
  decadevs_docker_damilola:
    container_name: decadevs-docker-damilola
    image: decadevs-docker-damilola
    build: ./
    ports:
      - "8532:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3340:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: damilola
      MYSQL_USER: damilola
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: root